window.addEventListener('load',()=>{createSparks();setTimeout(()=>document.body.classList.add('loaded'),1600)});
function createSparks(){for(let i=0;i<32;i++){let s=document.createElement('span');s.className='spark';s.style.left=Math.random()*100+'%';s.style.top=Math.random()*100+'%';s.style.animationDelay=(Math.random()*4)+'s';s.style.animationDuration=(3+Math.random()*5)+'s';document.body.appendChild(s)}}
const whatsappNumber='94740301177';let cart=[],activeCat='All',editIndex=null,wishlistOnly=false;let wishes=JSON.parse(localStorage.getItem('cnkWishes')||'[]');
const defaults=[{name:'Gear 5 Oversized Tee',price:2000,img:'assets/shirt-onepiece.png',cat:'Graphic',tag:'BEST SELLER',stock:true,desc:'Black oversized graphic tee • COD available',sizes:['M','L','XL']},{name:'Ulquiorra Oversized Tee',price:2000,img:'assets/shirt-bleach.png',cat:'Graphic',tag:'NEW ARRIVAL',stock:true,desc:'Black oversized graphic tee • COD available',sizes:['M','L','XL']}];
let products=JSON.parse(localStorage.getItem('cnkProducts')||'null')||defaults;
function saveStore(){localStorage.setItem('cnkProducts',JSON.stringify(products))}
function saveWishes(){localStorage.setItem('cnkWishes',JSON.stringify(wishes))}
function go(x){document.querySelector(x).scrollIntoView({behavior:'smooth'})}
function toggleMenu(){mobileMenu.classList.toggle('open');menuBtn.textContent=mobileMenu.classList.contains('open')?'✕':'☰'}
document.querySelectorAll('#mobileMenu a').forEach(a=>a.addEventListener('click',()=>{mobileMenu.classList.remove('open');menuBtn.textContent='☰'}));
function renderFilters(){let cats=['All',...new Set(products.map(p=>p.cat||'Other'))];filters.innerHTML=cats.map(c=>`<button class="filter ${c==activeCat?'active':''}" onclick="activeCat='${c}';renderProducts();renderFilters()">${c}</button>`).join('')}
function toggleWishlistOnly(){wishlistOnly=!wishlistOnly;document.querySelector('.wishlistOnly').classList.toggle('active',wishlistOnly);renderProducts()}
function toggleWish(i,e){e.stopPropagation();wishes.includes(i)?wishes=wishes.filter(x=>x!==i):wishes.push(i);saveWishes();renderProducts()}
function getFiltered(){let q=(searchBox?.value||'').toLowerCase();return products.filter((p,i)=>(activeCat=='All'||p.cat==activeCat)&&(!wishlistOnly||wishes.includes(i))&&(`${p.name} ${p.desc} ${p.cat} ${p.tag}`.toLowerCase().includes(q)))}
function renderProducts(){let list=getFiltered();document.getElementById('products').innerHTML=list.length?list.map(p=>{let realIndex=products.indexOf(p);let sizes=(p.sizes||['M','L','XL']);return `<article class="product" onclick="openModal(${realIndex})"><span class="tag">${p.tag||'NEW'}</span><span class="stock ${p.stock?'in':'out'}">${p.stock?'● IN STOCK':'● OUT OF STOCK'}</span><button class="wish ${wishes.includes(realIndex)?'active':''}" onclick="toggleWish(${realIndex},event)"> ${wishes.includes(realIndex)?'♥':'♡'}</button><div class="product-img"><img loading="lazy" src="${p.img}" alt="${p.name}"></div><div class="info"><h3>${p.name}</h3><p class="muted">${p.desc||''}</p><div class="badges"><span>220 GSM</span><span>100% Cotton</span><span>Oversized Fit</span><span>COD</span></div><div class="row" onclick="event.stopPropagation()"><select id="s${realIndex}">${sizes.map(s=>`<option>${s}</option>`).join('')}</select><input id="q${realIndex}" class="qty" type="number" min="1" value="1"><b>Rs. ${p.price}</b><button class="add" ${!p.stock?'disabled':''} onclick="addToCart(${realIndex})">Add to Cart</button></div></div></article>`}).join(''):'<p class="muted">No products found.</p>'}
function addToCart(i,size=null,qty=null){let p=products[i];if(!p.stock)return;let selected=size||document.getElementById('s'+i)?.value||(p.sizes||['M'])[0];let amount=qty||Math.max(1,parseInt(document.getElementById('q'+i)?.value||1));let found=cart.find(x=>x.name===p.name&&x.size===selected);if(found)found.qty+=amount;else cart.push({name:p.name,price:+p.price,size:selected,qty:amount});renderCart();cartCount.classList.add('cart-bounce');setTimeout(()=>cartCount.classList.remove('cart-bounce'),450);toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1200)}
function changeQty(idx,delta){cart[idx].qty+=delta;if(cart[idx].qty<=0)cart.splice(idx,1);renderCart()}
function cartHtml(){return cart.length?cart.map((i,idx)=>`<div class="cart-item"><span>${i.name} <b>(${i.size})</b><br><small>Rs. ${i.price} × ${i.qty}</small><div class="cart-qty"><button onclick="changeQty(${idx},-1)">−</button><b>${i.qty}</b><button onclick="changeQty(${idx},1)">+</button></div></span><button class="remove" onclick="cart.splice(${idx},1);renderCart()">Remove</button></div>`).join(''):'<p class="muted">Cart is empty. Add a T-shirt first.</p>'}
function renderCart(){let count=cart.reduce((s,i)=>s+i.qty,0);cartCount.textContent=count;bottomCount.textContent=count;let total=cart.reduce((s,i)=>s+i.price*i.qty,0);totalEl= document.getElementById('total'); totalEl.textContent=total;drawerTotal.textContent=total;cartItems.innerHTML=cartHtml();drawerItems.innerHTML=cartHtml()}
function sendOrder(e){e.preventDefault();if(!cart.length)return alert('Please add at least one T-shirt.');let total=cart.reduce((s,i)=>s+i.price*i.qty,0),items=cart.map((i,n)=>`${n+1}. ${i.name} - Size ${i.size} - Qty ${i.qty} - Rs. ${i.price*i.qty}`).join('%0A');let msg=`Hello CNK WEAR,%0AI want to place an order.%0A%0AItems:%0A${items}%0A%0ATotal: Rs. ${total}%0A%0AName: ${encodeURIComponent(name.value)}%0APhone: ${encodeURIComponent(phone.value)}%0AAddress: ${encodeURIComponent(address.value)}%0ANote: ${encodeURIComponent(note.value||'COD')}`;window.open(`https://wa.me/${whatsappNumber}?text=${msg}`,'_blank')}
function openModal(i){let p=products[i],sizes=(p.sizes||['M','L','XL']);modalImg.src=p.img;modalName.textContent=p.name;modalDesc.textContent=p.desc||'';modalPrice.textContent='Rs. '+p.price;modalStock.className='stock '+(p.stock?'in':'out');modalStock.textContent=p.stock?'● IN STOCK':'● OUT OF STOCK';modalSize.innerHTML=sizes.map(s=>`<option>${s}</option>`).join('');modalQty.value=1;modalAdd.disabled=!p.stock;modalAdd.onclick=()=>{addToCart(i,modalSize.value,Math.max(1,parseInt(modalQty.value||1)));productModal.classList.remove('open');openCart()};productModal.classList.add('open')}
function closeModal(e){if(e.target.id==='productModal'||e.target.classList.contains('close'))productModal.classList.remove('open')}
function openCart(){cartDrawer.classList.add('open');shade.classList.add('open')}
function closeCart(){cartDrawer.classList.remove('open');shade.classList.remove('open')}
function openAdmin(){let pass=prompt('Admin password');if(pass==='CNK2026'){adminPanel.classList.add('open');renderAdmin()}else if(pass)alert('Wrong password')}
function closeAdmin(){adminPanel.classList.remove('open');editIndex=null;clearForm()}
document.addEventListener('keydown',e=>{if(e.ctrlKey&&e.shiftKey&&e.key.toLowerCase()==='a')openAdmin();if(e.key==='Escape'){productModal.classList.remove('open');closeCart()}});if(location.hash==='#admin')setTimeout(openAdmin,500);
function clearForm(){pName.value=pPrice.value=pImage.value=pCat.value=pTag.value=pDesc.value=pSizes.value='';pStock.value='true'}
function saveProduct(){let obj={name:pName.value,price:+pPrice.value,img:pImage.value||'assets/logo.png',cat:pCat.value||'Other',tag:pTag.value||'NEW',stock:pStock.value==='true',desc:pDesc.value,sizes:(pSizes.value||'M,L,XL').split(',').map(s=>s.trim())};if(!obj.name||!obj.price)return alert('Add product name and price');if(editIndex===null)products.push(obj);else products[editIndex]=obj;saveStore();clearForm();editIndex=null;renderFilters();renderProducts();renderAdmin()}
function renderAdmin(){adminList.innerHTML=products.map((p,i)=>`<div class="admin-row"><span>${p.name} - Rs. ${p.price} - ${p.stock?'In Stock':'Out of Stock'}</span><button class="pill" onclick="editProduct(${i})">Edit</button><button class="pill" onclick="products.splice(${i},1);saveStore();renderFilters();renderProducts();renderAdmin()">Delete</button></div>`).join('')}
function editProduct(i){let p=products[i];editIndex=i;pName.value=p.name;pPrice.value=p.price;pImage.value=p.img;pCat.value=p.cat;pTag.value=p.tag;pStock.value=String(!!p.stock);pDesc.value=p.desc||'';pSizes.value=(p.sizes||[]).join(',')}
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));renderFilters();renderProducts();renderCart();
